name: Flutter CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-test-deploy:
    name: Build, Test, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.x  # Use the Flutter version you need
          cache: true

      - name: Navigate to Flutter Project Directory
        run: cd App

      - name: Install Dependencies
        run: |
          cd App
          flutter pub get

      - name: Run Flutter Analyzer
        run: |
          cd App
          flutter analyze

      - name: Run Flutter Tests
        run: |
          cd App
          flutter test

      - name: Build APK
        run: |
          cd App
          flutter build apk --release || true

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            App/build/app/outputs/flutter-apk/app-release.apk
            App/build/app/outputs/bundle/release/app-release.aab

      - name: Get version number from GitHub Run ID
        id: version
        run: echo "VERSION_NAME=1.0.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Tag the release with version
        run: |
          git tag -a "v1.0.${{ github.run_number }}" -m "Release version 1.0.${{ github.run_number }}"
          git push origin "v1.0.${{ github.run_number }}"  # Push the tag to GitHub

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: App/build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      # Deployment Steps (Optional)
      # - You can add deployment to Firebase, Play Store, or App Store if needed
