name: Flutter CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.x  # Change this to your Flutter version
          channel: stable

      - name: Install Dependencies
        run: flutter pub get
        working-directory: app  # Since your Flutter project is inside 'app'

      - name: Run Linter
        run: flutter analyze
        working-directory: app

      - name: Run Tests
        run: flutter test
        working-directory: app

      - name: Build APK
        run: flutter build apk --release
        working-directory: app

      - name: Build App Bundle (AAB)
        run: flutter build appbundle --release
        working-directory: app

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: app/build/app/outputs/flutter-apk/app-release.apk
